[build]
  command   = "npm run build"
  publish   = ".next"

[build.environment]
  DEMO_MODE        = "true"
  NEXTAUTH_SECRET  = "uisa-demo-secret-netlify-2025"
  DATABASE_URL     = "file:./prisma/dev.db"
  NODE_VERSION     = "20"
